name: PR Check with Dynamic Arguments

on:
  pull_request:
    paths:
      - 'cfgfiles/**'
    branches:
      - AUTOMATION
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Changed Files
        run: git diff --name-only HEAD^1 HEAD

      - name: Debug Info
        run: |
          echo "Current Branch: $(git branch --show-current)"
          git diff --name-only HEAD^1 HEAD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: List files in workspace
        run: ls -R

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi

      - name: Find Config Files
        id: find-configs
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD | grep '^cfgfiles/.*\.cfg$' || true)

          DEFAULT_FILE=$(echo "$CHANGED_FILES" | grep 'default\.cfg' || true)
          INPUT_FILES=$(echo "$CHANGED_FILES" | grep -v 'default\.cfg' || true)

          echo "Changed Files: $CHANGED_FILES"
          echo "Default File: $DEFAULT_FILE"
          echo "Input Files: $INPUT_FILES"

          echo "default_file=$DEFAULT_FILE" >> $GITHUB_ENV
          echo "input_files<<EOF" >> $GITHUB_ENV
          echo "$INPUT_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run comparison script
        id: run_script
        run: |
          set -x   # Enable debug mode to print each command before running
          python utils/check_cfg_params.py --input_files "${{ env.input_files }}" --default_file "${{ env.default_file }}"
          set +x   # Disable debug mode
